; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.27"
projects[admin_menu][subdir] = "../drupal"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dafto][download][type] = ""
projects[dafto][download][url] = ""
projects[dafto][type] = "profile"

; Modules
projects[admin_menu][version] = "3.0-rc4"
projects[admin_menu][subdir] = "contrib"

projects[ctools][version] = "1.4"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[features][version] = "2.0"

projects[field_collection][version] = "1.0-beta7"

projects[field_group][version] = "1.1"

projects[file_entity][version] = "2.0-alpha3"

projects[i18n][version] = "1.11"

projects[panels][version] = "3.4"

projects[jcarousel][version] = "2.6"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.1"

projects[link][version] = "1.2"

projects[media][version] = "2.0-alpha3"

projects[media_youtube][version] = "2.0-rc4"

projects[module_filter][version] = "1.7"

projects[multiupload_filefield_widget][version] = "1.11"

projects[multiupload_imagefield_widget][version] = "1.2"

projects[references][version] = "2.1"

projects[panels_everywhere][version] = "1.0-rc1"

projects[pathauto][version] = "1.2"

projects[semanticviews][version] = "1.0-alpha1"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[variable][version] = "2.2"

projects[views][version] = "3.7"

; Themes
projects[adaptivetheme][version] = "3.2"

projects[at_panels_everywhere][version] = "3.0-rc1"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[profiler][download][type] = "git"
libraries[profiler][download][url] = "http://git.drupal.org/project/profiler.git"
libraries[profiler][directory_name] = "profiler"
libraries[profiler][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.4.0/ckeditor_4.4.0_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = "get"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox/archive/master.zip"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"