#!/bin/bash
#
# run Drupal cron job
wget -O - -q -t 1 http://[siteurl]?cron_key=
echo "Cron successfully run!";


# Access first page to warm cache
page="http://www.[siteurl]";
wget -O - -q -t 1 $page
